# This file was generated by GoReleaser. DO NOT EDIT.
cask "constitution" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "011401ec97dc5f549ed68c0682919791bb3214bc73120db773a412385ac1f917"
      url "https://github.com/kentra-io/adr-sourced-constitution/releases/download/v#{version}/constitution_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6bd0a09a2f7c66d968a36223a3e7ef32793fa7176c6d0413931ebb577cb5aed4"
      url "https://github.com/kentra-io/adr-sourced-constitution/releases/download/v#{version}/constitution_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4aad5eb1acf5c6e7cd17e4984a9e9d33c3b7836de3be65dcdb77ebc634394cc9"
      url "https://github.com/kentra-io/adr-sourced-constitution/releases/download/v#{version}/constitution_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "26b69e6581be14eb0bb1b01f6bfffd24015c9f297519e92bd9a2c861ec6f5f4a"
      url "https://github.com/kentra-io/adr-sourced-constitution/releases/download/v#{version}/constitution_#{version}_linux_arm64.tar.gz"
    end
  end

  name "constitution"
  desc "Append-only MADR ADR log rendered to a deterministic constitution.md projection"
  homepage "https://github.com/kentra-io/adr-sourced-constitution"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "constitution"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/constitution"]
    end
  end

  # No zap stanza required

end
