# This file was generated by GoReleaser. DO NOT EDIT.
cask "constitution" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "c2d22662184f66cdf9b71aab21a14344aa7ec4ca2034351d16ca31103646b5c4"
      url "https://github.com/kentra-io/adr-sourced-constitution/releases/download/v#{version}/constitution_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a3d8aab9dccee1b3be14e416b960518c91df1d106da604b22ea544f94ade8ad"
      url "https://github.com/kentra-io/adr-sourced-constitution/releases/download/v#{version}/constitution_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "874ffca7ee0e88e0f7a6e70d327b91cedc9606d1be83d8f7d42607e50b4bb5ce"
      url "https://github.com/kentra-io/adr-sourced-constitution/releases/download/v#{version}/constitution_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "df9f5ddd21dc80bcb8f039f9e3e1aa237da66f0084aac95b0c8835feb4217443"
      url "https://github.com/kentra-io/adr-sourced-constitution/releases/download/v#{version}/constitution_#{version}_linux_arm64.tar.gz"
    end
  end

  name "constitution"
  desc "Append-only MADR ADR log rendered to a deterministic constitution.md projection"
  homepage "https://github.com/kentra-io/adr-sourced-constitution"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "constitution"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/constitution"]
    end
  end

  # No zap stanza required

end
