# This file was generated by GoReleaser. DO NOT EDIT.
cask "constitution" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "f128714f18528de8fcf00f43b99bb693e4de44d29e6d47efc14de8ca345f9f45"
      url "https://github.com/kentra-io/adr-sourced-constitution/releases/download/v#{version}/constitution_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cdb14063c43813c97ee9a14d0d78ce2cd7dcf83008fec5661cc16a458aae941f"
      url "https://github.com/kentra-io/adr-sourced-constitution/releases/download/v#{version}/constitution_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c7f11ec95796e38556a98349bd35af0f788e13c844a594a818ff538b9634f7ef"
      url "https://github.com/kentra-io/adr-sourced-constitution/releases/download/v#{version}/constitution_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "924c5ccc66d49798fc844f7aad5336ba7184ab55762208f730b7a6c494ea5f9a"
      url "https://github.com/kentra-io/adr-sourced-constitution/releases/download/v#{version}/constitution_#{version}_linux_arm64.tar.gz"
    end
  end

  name "constitution"
  desc "Append-only MADR ADR log rendered to a deterministic constitution.md projection"
  homepage "https://github.com/kentra-io/adr-sourced-constitution"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "constitution"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/constitution"]
    end
  end

  # No zap stanza required

end
