# This file was generated by GoReleaser. DO NOT EDIT.
cask "lifecycle" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "f052e394ffed5b34e2b4ca689e3f99e27e5509a5c9cebdc40e737702f38ed8ca"
      url "https://github.com/kentra-io/spec-lifecycle/releases/download/v#{version}/lifecycle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f76e733d069eb908d993b593f5893b9caff06c6e2315d3e326ef4ba0712310b2"
      url "https://github.com/kentra-io/spec-lifecycle/releases/download/v#{version}/lifecycle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "33a62f7bba23fd5d870628a5fa7630bb583faaa7ebd4f9db1c16d38c3bfaf57c"
      url "https://github.com/kentra-io/spec-lifecycle/releases/download/v#{version}/lifecycle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5de48ea7be107891c5fd3d8db07b997a0c86ee7fb3f00c4cf63469e3f8993ed4"
      url "https://github.com/kentra-io/spec-lifecycle/releases/download/v#{version}/lifecycle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lifecycle"
  desc "Staged, gated OpenSpec-format change lifecycle — single static Go binary, no Node/OpenSpec runtime"
  homepage "https://github.com/kentra-io/spec-lifecycle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lifecycle"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lifecycle"]
    end
  end

  # No zap stanza required

end
