# This file was generated by GoReleaser. DO NOT EDIT.
cask "lifecycle" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "04c02a2e4f00ef22e04c37ee2ddf44da755c337ad4c39f0d9028997e51ca81da"
      url "https://github.com/kentra-io/spec-lifecycle/releases/download/v#{version}/lifecycle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c04161cfa62f14ea7fd1c8129355c8689dda649cc09f8a367971266f80c02cc"
      url "https://github.com/kentra-io/spec-lifecycle/releases/download/v#{version}/lifecycle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4128d099de74bdce28035467481ff1a324f54826ac571bb72b95500d028b8814"
      url "https://github.com/kentra-io/spec-lifecycle/releases/download/v#{version}/lifecycle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "66edddc0cebb3d216e263835265428fa859848070ba7c0c1909d8041cf330403"
      url "https://github.com/kentra-io/spec-lifecycle/releases/download/v#{version}/lifecycle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lifecycle"
  desc "Staged, gated OpenSpec-format change lifecycle — single static Go binary, no Node/OpenSpec runtime"
  homepage "https://github.com/kentra-io/spec-lifecycle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lifecycle"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lifecycle"]
    end
  end

  # No zap stanza required

end
