# This file was generated by GoReleaser. DO NOT EDIT.
cask "milestoned-plan-dag" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "8431ff3f663db8a0d894f208c5ded463d42052b13d8f46f1fe131eb1c5a6a28c"
      url "https://github.com/kentra-io/milestoned-plan-dag/releases/download/v#{version}/milestoned-plan-dag_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "99d1eca44324293a6e94a9fe3ecf655538d14d74a18b3530556d9332cbadb1ea"
      url "https://github.com/kentra-io/milestoned-plan-dag/releases/download/v#{version}/milestoned-plan-dag_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "832bfcb16b2fdfff1251cbcf0c4ee19efec93589668acd221b9fd9a02d876730"
      url "https://github.com/kentra-io/milestoned-plan-dag/releases/download/v#{version}/milestoned-plan-dag_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "31109d7bd65aff06f5e9ce852ecdfe03965cb44d75fa43f2c2ea4ff92dfef3c2"
      url "https://github.com/kentra-io/milestoned-plan-dag/releases/download/v#{version}/milestoned-plan-dag_#{version}_linux_arm64.tar.gz"
    end
  end

  name "milestoned-plan-dag"
  desc "Machine-first YAML plan format — a DAG of verifiable milestones, with a validating single-binary CLI"
  homepage "https://github.com/kentra-io/milestoned-plan-dag"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "milestoned-plan-dag"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/milestoned-plan-dag"]
    end
  end

  # No zap stanza required

end
