# This file was generated by GoReleaser. DO NOT EDIT.
cask "milestoned-plan-dag" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "be2b77854066d3d16147e548d437a56576543e82e8fcf9612090747e84c2acdf"
      url "https://github.com/kentra-io/milestoned-plan-dag/releases/download/v#{version}/milestoned-plan-dag_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "736edcce5587bfceba8d52e6788f980a6303c888a60f535d8f8c7bec6f0d002c"
      url "https://github.com/kentra-io/milestoned-plan-dag/releases/download/v#{version}/milestoned-plan-dag_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4fdcfca935747418abd517ca71a70be8d634641b047ea6ec2c3760618a2ec507"
      url "https://github.com/kentra-io/milestoned-plan-dag/releases/download/v#{version}/milestoned-plan-dag_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e337b0674d318febfa6601159f3266142d7ee62f2cc6b48d18f1151743cb1de8"
      url "https://github.com/kentra-io/milestoned-plan-dag/releases/download/v#{version}/milestoned-plan-dag_#{version}_linux_arm64.tar.gz"
    end
  end

  name "milestoned-plan-dag"
  desc "Machine-first YAML plan format — a DAG of verifiable milestones, with a validating single-binary CLI"
  homepage "https://github.com/kentra-io/milestoned-plan-dag"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "milestoned-plan-dag"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/milestoned-plan-dag"]
    end
  end

  # No zap stanza required

end
