# This file was generated by GoReleaser. DO NOT EDIT.
cask "milestoned-plan-dag" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "e3de7f165095b07df898051e19c982f9d4b1a3997f075cfde4a9a211a8d11a1c"
      url "https://github.com/kentra-io/milestoned-plan-dag/releases/download/v#{version}/milestoned-plan-dag_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d6685ab7678b97ff3ba8c252582fa9240de65f6661575da55527bf6960f5b0f"
      url "https://github.com/kentra-io/milestoned-plan-dag/releases/download/v#{version}/milestoned-plan-dag_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a9c44b946643908a17961311c8f8e8ba4e55790f4642ee9eeb5f916c5fe919c2"
      url "https://github.com/kentra-io/milestoned-plan-dag/releases/download/v#{version}/milestoned-plan-dag_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "268f901aef053e6ec1262135b760510c83b137bde3dab721617644ba91dad182"
      url "https://github.com/kentra-io/milestoned-plan-dag/releases/download/v#{version}/milestoned-plan-dag_#{version}_linux_arm64.tar.gz"
    end
  end

  name "milestoned-plan-dag"
  desc "Machine-first YAML plan format — a DAG of verifiable milestones, with a validating single-binary CLI"
  homepage "https://github.com/kentra-io/milestoned-plan-dag"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "milestoned-plan-dag"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/milestoned-plan-dag"]
    end
  end

  # No zap stanza required

end
